"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, Bot, Boxes, Check, CheckCircle2, ChevronRight, Clock3, Cloud, Database, GitBranch, LayoutDashboard, Mail, Menu, MoreHorizontal, Play, Plus, RefreshCw, Search, Settings, Sparkles, Target, Webhook, X, Zap } from "lucide-react";

type Automation = { id:number; name:string; description:string; triggerType:string; actionType:string; status:string; runs:number; successRate:number };
type Run = { id:number; automationId:number; automationName:string; contactName:string; classification:string; priority:string; status:string; attempts:number; durationMs:number; timeSavedMinutes:number; provider:string; emailDraft:string; createdAt:string };
type WebMcpTool={name:string;title:string;description:string;inputSchema:Record<string,unknown>;annotations:Record<string,boolean>;execute:(input:unknown)=>Promise<unknown>};
const sampleAutomations: Automation[] = [
  { id:1,name:"Qualificar novos leads",description:"Classifica contatos e cria tarefas no CRM",triggerType:"Novo formulário",actionType:"IA + CRM",status:"active",runs:128,successRate:98.4 },
  { id:2,name:"Resposta de boas-vindas",description:"Personaliza e envia o primeiro contato",triggerType:"Lead qualificado",actionType:"E-mail",status:"active",runs:96,successRate:97.9 },
  { id:3,name:"Recuperar oportunidades",description:"Reengaja leads sem atividade há 7 dias",triggerType:"Agendamento",actionType:"CRM + E-mail",status:"paused",runs:42,successRate:95.2 },
];
const sampleRuns: Run[] = [
  { id:1,automationId:1,automationName:"Qualificar novos leads",contactName:"Marina Costa",classification:"Lead quente",priority:"Alta",status:"success",attempts:1,durationMs:1240,timeSavedMinutes:12,provider:"groq",emailDraft:"Olá, Marina! Vamos conversar sobre sua automação.",createdAt:new Date().toISOString() },
  { id:2,automationId:2,automationName:"Resposta de boas-vindas",contactName:"Lucas Martins",classification:"Oportunidade",priority:"Média",status:"success",attempts:1,durationMs:880,timeSavedMinutes:8,provider:"gemini",emailDraft:"Olá, Lucas! Obrigada pelo contato.",createdAt:new Date(Date.now()-12*60*1000).toISOString() },
  { id:3,automationId:1,automationName:"Qualificar novos leads",contactName:"Beatriz Alves",classification:"Nutrição",priority:"Baixa",status:"retry",attempts:2,durationMs:2100,timeSavedMinutes:10,provider:"simulation",emailDraft:"",createdAt:new Date(Date.now()-31*60*1000).toISOString() },
];
const statusLabel:Record<string,string>={success:"Concluído",retry:"Nova tentativa",active:"Ativa",paused:"Pausada"};

export default function Home(){
  const [automations,setAutomations]=useState<Automation[]>(sampleAutomations); const [runs,setRuns]=useState<Run[]>(sampleRuns);
  const [tab,setTab]=useState<"overview"|"automations"|"runs">("overview"); const [dialog,setDialog]=useState(false); const [about,setAbout]=useState(false); const [mobileNav,setMobileNav]=useState(false); const [loading,setLoading]=useState(false); const [notice,setNotice]=useState("");
  const [form,setForm]=useState({name:"",description:"",triggerType:"Novo formulário",actionType:"IA + CRM"});
  const loadData=useCallback(async()=>{try{const response=await fetch("/api/dashboard");if(!response.ok)return;const data=await response.json();if(data.automations?.length)setAutomations(data.automations);if(data.runs?.length)setRuns(data.runs)}catch{}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void loadData(),0);return()=>window.clearTimeout(timer)},[loadData]);
  useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool?:(tool:WebMcpTool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=context.registerTool.bind(context);void Promise.resolve(register({name:"create_automation",title:"Criar automação",description:"Cria e salva uma nova automação no painel BrunaFlow AI.",inputSchema:{type:"object",properties:{name:{type:"string"},description:{type:"string"},triggerType:{type:"string"},actionType:{type:"string"}},required:["name","triggerType","actionType"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const payload=input as typeof form;const response=await fetch("/api/dashboard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"automation",...payload})});if(!response.ok)throw new Error("Não foi possível criar a automação.");const data=await response.json();await loadData();return{id:data.automation.id,status:"created"}}},{signal:lifecycle.signal})).catch(()=>undefined);return()=>lifecycle.abort()},[loadData]);
  const metrics=useMemo(()=>{const successful=runs.filter(r=>r.status==="success").length;return{executions:automations.reduce((sum,item)=>sum+item.runs,0)+runs.length,success:runs.length?((successful/runs.length)*100).toFixed(1):"0",saved:Math.round(runs.reduce((sum,item)=>sum+item.timeSavedMinutes,0)/60*10)/10}},[automations,runs]);
  async function createAutomation(event:React.FormEvent){event.preventDefault();if(!form.name.trim())return;setLoading(true);try{const response=await fetch("/api/dashboard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"automation",...form})});if(!response.ok)throw new Error();const data=await response.json();setAutomations(current=>[data.automation,...current]);setDialog(false);setForm({name:"",description:"",triggerType:"Novo formulário",actionType:"IA + CRM"});setNotice("Automação criada com sucesso")}catch{setNotice("Não foi possível salvar. Tente novamente.")}finally{setLoading(false);setTimeout(()=>setNotice(""),3000)}}
  async function runDemo(automation:Automation){setLoading(true);setNotice("Executando o fluxo…");try{const response=await fetch("/api/dashboard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"run",automationId:automation.id,automationName:automation.name})});if(!response.ok)throw new Error();const data=await response.json();setRuns(current=>[data.run,...current]);const source=data.run.provider==="groq"?"Groq":data.run.provider==="gemini"?"Gemini":"modo demonstração";setNotice(`Fluxo concluído com ${source}: lead classificado e tarefa criada`)}catch{setNotice("A execução falhou. Verifique a conexão e tente novamente.")}finally{setLoading(false);setTimeout(()=>setNotice(""),4000)}}
  const go=(next:typeof tab)=>{setTab(next);setMobileNav(false)};
  return <main className="app-shell">
    <aside className={`sidebar ${mobileNav?"open":""}`}><div className="brand"><span className="brand-mark"><GitBranch size={20}/></span><div><strong>BrunaFlow</strong><span>AI automation</span></div></div><nav><button className={tab==="overview"?"active":""} onClick={()=>go("overview")}><LayoutDashboard size={18}/>Visão geral</button><button className={tab==="automations"?"active":""} onClick={()=>go("automations")}><Zap size={18}/>Automações <span className="nav-count">{automations.length}</span></button><button className={tab==="runs"?"active":""} onClick={()=>go("runs")}><Activity size={18}/>Execuções</button></nav><div className="nav-section">Workspace</div><nav><button><Boxes size={18}/>Integrações</button><button><Webhook size={18}/>Webhooks</button><button><Settings size={18}/>Configurações</button></nav><div className="sidebar-footer"><div className="plan-pill"><Sparkles size={15}/><span><strong>Projeto de portfólio</strong><small>Ambiente demonstrativo</small></span></div><button onClick={()=>setAbout(true)} className="text-link">Como o projeto funciona <ArrowRight size={14}/></button></div></aside>
    <section className="content"><header className="topbar"><button className="icon-button menu" onClick={()=>setMobileNav(!mobileNav)}><Menu size={20}/></button><div className="search"><Search size={17}/><span>Buscar automações, execuções…</span></div><div className="top-actions"><span className="system-status"><i/>Sistema operacional</span><button className="avatar">BE</button></div></header><div className="page"><div className="page-heading"><div><span className="eyebrow">CENTRAL DE OPERAÇÕES</span><h1>{tab==="overview"?"Bom dia, Bruna.":tab==="automations"?"Suas automações":"Histórico de execuções"}</h1><p>{tab==="overview"?"Acompanhe seus fluxos e veja o trabalho acontecendo em tempo real.":tab==="automations"?"Crie, teste e gerencie processos inteligentes em um só lugar.":"Monitore cada etapa, tentativa e resultado dos seus fluxos."}</p></div><button className="primary" onClick={()=>setDialog(true)}><Plus size={18}/>Nova automação</button></div>
      {tab==="overview"&&<><div className="metrics"><Metric icon={<Activity/>} label="Execuções este mês" value={metrics.executions.toLocaleString("pt-BR")} hint="+18% vs. mês anterior" tone="violet"/><Metric icon={<CheckCircle2/>} label="Taxa de sucesso" value={`${metrics.success}%`} hint="Dentro da meta" tone="cyan"/><Metric icon={<Clock3/>} label="Tempo economizado" value={`${metrics.saved}h`} hint="Equivale a 3 dias úteis" tone="green"/><Metric icon={<Zap/>} label="Automações ativas" value={String(automations.filter(a=>a.status==="active").length)} hint={`${automations.length} fluxos configurados`} tone="pink"/></div><section className="spotlight"><div className="spotlight-copy"><span className="eyebrow light">FLUXO EM DESTAQUE</span><h2>Transforme cada novo contato em uma oportunidade.</h2><p>O BrunaFlow recebe o formulário, interpreta a intenção com IA, atualiza o CRM e prepara uma resposta personalizada — em segundos.</p><button onClick={()=>runDemo(automations[0])} disabled={loading}><Play size={16}/>{loading?"Executando…":"Executar demonstração"}</button></div><div className="flow-visual"><FlowNode icon={<Webhook/>} label="Formulário" sub="Novo contato"/><FlowLine/><FlowNode icon={<Bot/>} label="IA classifica" sub="Lead quente" active/><FlowLine/><FlowNode icon={<Target/>} label="CRM" sub="Tarefa criada"/><FlowLine/><FlowNode icon={<Mail/>} label="E-mail" sub="Resposta enviada"/></div></section><div className="grid-two"><AutomationList automations={automations.slice(0,3)} onRun={runDemo} onAll={()=>setTab("automations")}/><RunList runs={runs.slice(0,4)} onAll={()=>setTab("runs")}/></div></>}
      {tab==="automations"&&<div className="automation-grid">{automations.map(item=><article className="automation-card" key={item.id}><div className="card-top"><span className="automation-icon"><Zap size={20}/></span><span className={`state ${item.status}`}>{statusLabel[item.status]}</span></div><h3>{item.name}</h3><p>{item.description}</p><div className="mini-flow"><span>{item.triggerType}</span><ChevronRight size={14}/><span>{item.actionType}</span></div><div className="card-stats"><span><strong>{item.runs}</strong> execuções</span><span><strong>{item.successRate}%</strong> sucesso</span></div><button className="outline" onClick={()=>runDemo(item)}><Play size={15}/>Testar fluxo</button></article>)}</div>}
      {tab==="runs"&&<section className="panel full"><div className="panel-head"><div><h2>Execuções recentes</h2><p>Rastreamento detalhado de cada fluxo</p></div><button className="icon-button" onClick={()=>void loadData()}><RefreshCw size={17}/></button></div><RunTable runs={runs}/></section>}
    </div></section>
    {dialog&&<div className="modal-backdrop" onMouseDown={()=>setDialog(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setDialog(false)}><X size={18}/></button><span className="modal-icon"><Zap/></span><h2>Criar nova automação</h2><p>Configure um fluxo inteligente em poucos passos.</p><form onSubmit={createAutomation}><label>Nome da automação<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Qualificar leads do site" required/></label><label>Descrição<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="O que este fluxo resolve?"/></label><div className="form-row"><label>Gatilho<select value={form.triggerType} onChange={e=>setForm({...form,triggerType:e.target.value})}><option>Novo formulário</option><option>Novo webhook</option><option>Agendamento</option><option>Lead qualificado</option></select></label><label>Ação final<select value={form.actionType} onChange={e=>setForm({...form,actionType:e.target.value})}><option>IA + CRM</option><option>IA + E-mail</option><option>Criar tarefa</option><option>CRM + E-mail</option></select></label></div><button className="primary submit" disabled={loading}>{loading?"Salvando…":"Criar automação"}<ArrowRight size={17}/></button></form></div></div>}
    {about&&<div className="modal-backdrop" onMouseDown={()=>setAbout(false)}><div className="modal about" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setAbout(false)}><X size={18}/></button><span className="eyebrow">SOBRE O PROJETO</span><h2>Como o BrunaFlow AI funciona</h2><p>Este projeto de portfólio demonstra uma plataforma empresarial de automação com IA, do gatilho ao acompanhamento do resultado.</p><div className="about-steps"><div><Webhook/><span><b>1. Recebe</b><small>Formulário ou webhook inicia o fluxo.</small></span></div><div><Bot/><span><b>2. Entende</b><small>A IA classifica intenção e prioridade.</small></span></div><div><Database/><span><b>3. Organiza</b><small>O contato e a tarefa são enviados ao CRM.</small></span></div><div><Mail/><span><b>4. Responde</b><small>Uma mensagem personalizada é preparada.</small></span></div></div><div className="tech-note"><Cloud/><span><b>Arquitetura demonstrada</b><small>Next.js, TypeScript, Cloudflare Workers, D1, webhooks e processamento assíncrono simulado.</small></span></div></div></div>}
    {notice&&<div className="toast"><Check size={17}/>{notice}</div>}
  </main>
}
function Metric({icon,label,value,hint,tone}:{icon:React.ReactNode,label:string,value:string,hint:string,tone:string}){return <article className="metric"><span className={`metric-icon ${tone}`}>{icon}</span><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></article>}
function FlowNode({icon,label,sub,active}:{icon:React.ReactNode,label:string,sub:string,active?:boolean}){return <div className={`flow-node ${active?"active":""}`}><span>{icon}</span><b>{label}</b><small>{sub}</small></div>}
function FlowLine(){return <span className="flow-line"><i/></span>}
function AutomationList({automations,onRun,onAll}:{automations:Automation[],onRun:(a:Automation)=>void,onAll:()=>void}){return <section className="panel"><div className="panel-head"><div><h2>Automações</h2><p>Fluxos que trabalham por você</p></div><button className="text-link" onClick={onAll}>Ver todas <ArrowRight size={14}/></button></div><div className="list">{automations.map(item=><div className="automation-row" key={item.id}><span className="automation-icon"><Zap size={17}/></span><div><b>{item.name}</b><small>{item.description}</small></div><span className={`state ${item.status}`}>{statusLabel[item.status]}</span><button className="icon-button" onClick={()=>onRun(item)} title="Executar"><Play size={15}/></button></div>)}</div></section>}
function RunList({runs,onAll}:{runs:Run[],onAll:()=>void}){return <section className="panel"><div className="panel-head"><div><h2>Atividade recente</h2><p>Últimas execuções</p></div><button className="text-link" onClick={onAll}>Ver histórico <ArrowRight size={14}/></button></div><div className="list">{runs.map(run=><div className="run-row" key={run.id}><span className={`run-dot ${run.status}`}><Check size={13}/></span><div><b>{run.contactName}</b><small>{run.automationName}</small></div><div className="run-meta"><b>{run.classification}</b><small>{providerLabel(run.provider)} · {relativeTime(run.createdAt)}</small></div></div>)}</div></section>}
function RunTable({runs}:{runs:Run[]}){return <div className="table-wrap"><table><thead><tr><th>Contato</th><th>Automação</th><th>Classificação</th><th>IA</th><th>Status</th><th>Duração</th><th></th></tr></thead><tbody>{runs.map(run=><tr key={run.id}><td><strong>{run.contactName}</strong><small>Prioridade {run.priority.toLowerCase()}</small></td><td>{run.automationName}</td><td><span className="tag">{run.classification}</span></td><td>{providerLabel(run.provider)}</td><td><span className={`state ${run.status}`}>{statusLabel[run.status]||run.status}</span></td><td>{(run.durationMs/1000).toFixed(1)}s</td><td title={run.emailDraft||"Sem rascunho"}><MoreHorizontal size={17}/></td></tr>)}</tbody></table></div>}
function providerLabel(value:string){return value==="groq"?"Groq":value==="gemini"?"Gemini":"Demonstração"}
function relativeTime(value:string){const mins=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/60000));return mins<1?"agora":mins<60?`há ${mins} min`:`há ${Math.floor(mins/60)}h`}
