"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, Bot, Boxes, Check, CheckCircle2, ChevronRight, Clock3, Cloud, Database, GitBranch, Inbox, LayoutDashboard, LogOut, Mail, Menu, MoreHorizontal, Play, Plus, RefreshCw, Search, Settings, Sparkles, Target, Webhook, X, Zap } from "lucide-react";

type Automation={id:number;name:string;description:string;triggerType:string;actionType:string;status:string;runs:number;successRate:number};
type Run={id:number;automationId:number;automationName:string;contactName:string;classification:string;priority:string;status:string;attempts:number;durationMs:number;timeSavedMinutes:number;provider:string;emailDraft:string;createdAt:string};
type Metrics={executions:number;successRate:number;timeSavedMinutes:number};
type GmailStatus={connected:boolean;email?:string;inboxMessages?:number;unreadMessages?:number;sentMessages?:number;lastSyncedAt?:string;error?:string};
type WebMcpTool={name:string;title:string;description:string;inputSchema:Record<string,unknown>;annotations:Record<string,boolean>;execute:(input:unknown)=>Promise<unknown>};

const starterAutomations:Automation[]=[
  {id:1,name:"Qualificar novos leads",description:"Classifica contatos e cria tarefas no CRM",triggerType:"Novo formulário",actionType:"IA + CRM",status:"active",runs:0,successRate:0},
  {id:2,name:"Resposta de boas-vindas",description:"Personaliza e envia o primeiro contato",triggerType:"Lead qualificado",actionType:"E-mail",status:"active",runs:0,successRate:0},
  {id:3,name:"Recuperar oportunidades",description:"Reengaja leads sem atividade há 7 dias",triggerType:"Agendamento",actionType:"CRM + E-mail",status:"paused",runs:0,successRate:0},
];
const statusLabel:Record<string,string>={success:"Concluído",retry:"Nova tentativa",active:"Ativa",paused:"Pausada"};

export default function Home(){
  const [automations,setAutomations]=useState<Automation[]>(starterAutomations);const [runs,setRuns]=useState<Run[]>([]);const [metrics,setMetrics]=useState<Metrics>({executions:0,successRate:0,timeSavedMinutes:0});
  const [gmail,setGmail]=useState<GmailStatus>({connected:false});const [tab,setTab]=useState<"overview"|"automations"|"runs">("overview");const [dialog,setDialog]=useState(false);const [about,setAbout]=useState(false);const [mobileNav,setMobileNav]=useState(false);const [loading,setLoading]=useState(false);const [syncing,setSyncing]=useState(false);const [notice,setNotice]=useState("");
  const [form,setForm]=useState({name:"",description:"",triggerType:"Novo formulário",actionType:"IA + CRM"});const [testAutomation,setTestAutomation]=useState<Automation|null>(null);const [lead,setLead]=useState({contactName:"",contactEmail:"",message:"Quero automatizar os contatos que chegam pelo meu site."});

  const loadData=useCallback(async()=>{try{const response=await fetch("/api/dashboard");if(!response.ok)return;const data=await response.json();setAutomations(data.automations||[]);setRuns(data.runs||[]);if(data.metrics)setMetrics(data.metrics)}catch{}},[]);
  const loadGmail=useCallback(async(showFeedback=false)=>{setSyncing(true);try{const response=await fetch("/api/integrations/gmail/status");const data=await response.json();setGmail(data);if(showFeedback)setNotice(data.connected?"Gmail sincronizado com sucesso":data.error||"Nenhum Gmail conectado")}catch{if(showFeedback)setNotice("Não foi possível sincronizar o Gmail") }finally{setSyncing(false);if(showFeedback)setTimeout(()=>setNotice(""),4000)}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void loadData();void loadGmail();const result=new URLSearchParams(window.location.search).get("gmail");if(result){setNotice(result==="connected"?"Gmail conectado com sucesso":"Não foi possível conectar o Gmail");window.history.replaceState({},"",window.location.pathname);setTimeout(()=>setNotice(""),4000)}},0);return()=>window.clearTimeout(timer)},[loadData,loadGmail]);
  useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool?:(tool:WebMcpTool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=context.registerTool.bind(context);void Promise.resolve(register({name:"create_automation",title:"Criar automação",description:"Cria e salva uma nova automação no painel BrunaFlow AI.",inputSchema:{type:"object",properties:{name:{type:"string"},description:{type:"string"},triggerType:{type:"string"},actionType:{type:"string"}},required:["name","triggerType","actionType"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const payload=input as typeof form;const response=await fetch("/api/dashboard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"automation",...payload})});if(!response.ok)throw new Error("Não foi possível criar a automação.");const data=await response.json();await loadData();return{id:data.automation.id,status:"created"}}},{signal:lifecycle.signal})).catch(()=>undefined);return()=>lifecycle.abort()},[loadData]);

  const hoursSaved=useMemo(()=>Math.round(metrics.timeSavedMinutes/60*10)/10,[metrics.timeSavedMinutes]);
  async function createAutomation(event:React.FormEvent){event.preventDefault();if(!form.name.trim())return;setLoading(true);try{const response=await fetch("/api/dashboard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"automation",...form})});if(!response.ok)throw new Error();const data=await response.json();setAutomations(current=>[data.automation,...current]);setDialog(false);setForm({name:"",description:"",triggerType:"Novo formulário",actionType:"IA + CRM"});setNotice("Automação criada com sucesso")}catch{setNotice("Não foi possível salvar. Tente novamente.")}finally{setLoading(false);setTimeout(()=>setNotice(""),3000)}}
  async function runFlow(event:React.FormEvent){event.preventDefault();if(!testAutomation)return;setLoading(true);setNotice("Executando o fluxo…");try{const response=await fetch("/api/dashboard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"run",automationId:testAutomation.id,automationName:testAutomation.name,...lead})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Falha");setTestAutomation(null);await Promise.all([loadData(),loadGmail()]);const source=data.run.provider==="groq"?"Groq":data.run.provider==="gemini"?"Gemini":"modo demonstração";setNotice(`Fluxo concluído com ${source}. E-mail enviado por ${data.email.sender}.`)}catch(error){setNotice(error instanceof Error?error.message:"A execução falhou. Tente novamente.")}finally{setLoading(false);setTimeout(()=>setNotice(""),5000)}}
  function openTest(automation:Automation){if(!gmail.connected){setNotice("Conecte seu Gmail para usar sua conta como remetente.");setTimeout(()=>setNotice(""),4000);return}setTestAutomation(automation);setLead({contactName:"",contactEmail:gmail.email||"",message:"Quero automatizar os contatos que chegam pelo meu site."})}
  async function disconnectGmail(){setSyncing(true);try{await fetch("/api/integrations/gmail/disconnect",{method:"POST"});setGmail({connected:false});setNotice("Gmail desconectado") }finally{setSyncing(false);setTimeout(()=>setNotice(""),3000)}}
  const go=(next:typeof tab)=>{setTab(next);setMobileNav(false)};

  return <main className="app-shell">
    <aside className={`sidebar ${mobileNav?"open":""}`}><div className="brand"><span className="brand-mark"><GitBranch size={20}/></span><div><strong>BrunaFlow</strong><span>AI automation</span></div></div><nav><button className={tab==="overview"?"active":""} onClick={()=>go("overview")}><LayoutDashboard size={18}/>Visão geral</button><button className={tab==="automations"?"active":""} onClick={()=>go("automations")}><Zap size={18}/>Automações <span className="nav-count">{automations.length}</span></button><button className={tab==="runs"?"active":""} onClick={()=>go("runs")}><Activity size={18}/>Execuções</button></nav><div className="nav-section">Workspace</div><nav><button onClick={()=>void loadGmail(true)}><Boxes size={18}/>Integrações</button><button><Webhook size={18}/>Webhooks</button><button><Settings size={18}/>Configurações</button></nav><div className="sidebar-footer"><div className="plan-pill"><Sparkles size={15}/><span><strong>Projeto de portfólio</strong><small>Dados do visitante isolados</small></span></div><button onClick={()=>setAbout(true)} className="text-link">Como o projeto funciona <ArrowRight size={14}/></button><a href="/privacidade" className="privacy-link">Privacidade e dados</a></div></aside>
    <section className="content"><header className="topbar"><button className="icon-button menu" onClick={()=>setMobileNav(!mobileNav)}><Menu size={20}/></button><div className="search"><Search size={17}/><span>Buscar automações, execuções…</span></div><div className="top-actions"><span className={`system-status ${gmail.connected?"":"offline"}`}><i/>{gmail.connected?`Gmail: ${gmail.email}`:"Gmail não conectado"}</span><button className="avatar">{gmail.email?.slice(0,2).toUpperCase()||"BF"}</button></div></header>
      <div className="page"><div className="page-heading"><div><span className="eyebrow">CENTRAL DE OPERAÇÕES</span><h1>{tab==="overview"?"Sua central de automações":tab==="automations"?"Suas automações":"Histórico de execuções"}</h1><p>{tab==="overview"?"Métricas calculadas somente a partir das suas execuções e da conta conectada.":tab==="automations"?"Crie, teste e gerencie processos inteligentes em um só lugar.":"Monitore cada etapa, tentativa e resultado dos seus fluxos."}</p></div><button className="primary" onClick={()=>setDialog(true)}><Plus size={18}/>Nova automação</button></div>
        {tab==="overview"&&<><GmailConnection gmail={gmail} syncing={syncing} onSync={()=>void loadGmail(true)} onDisconnect={()=>void disconnectGmail()}/><div className="metrics"><Metric icon={<Activity/>} label="Execuções registradas" value={String(metrics.executions)} hint={metrics.executions?"Calculado pelo histórico real":"Execute um fluxo para começar"} tone="violet"/><Metric icon={<CheckCircle2/>} label="Taxa de sucesso" value={`${metrics.successRate}%`} hint={metrics.executions?`${metrics.executions} execução${metrics.executions===1?"":"ões"} analisada${metrics.executions===1?"":"s"}`:"Sem dados suficientes"} tone="cyan"/><Metric icon={<Clock3/>} label="Tempo economizado" value={`${hoursSaved}h`} hint={`${metrics.timeSavedMinutes} minutos registrados`} tone="green"/><Metric icon={<Inbox/>} label="Não lidos no Gmail" value={gmail.connected?String(gmail.unreadMessages||0):"—"} hint={gmail.connected?`${gmail.inboxMessages||0} mensagens na caixa de entrada`:"Conecte a conta para sincronizar"} tone="pink"/></div><section className="spotlight"><div className="spotlight-copy"><span className="eyebrow light">FLUXO EM DESTAQUE</span><h2>Transforme cada novo contato em uma oportunidade.</h2><p>O BrunaFlow recebe o formulário, interpreta a intenção com IA e envia a resposta usando a conta Gmail conectada.</p><button onClick={()=>openTest(automations[0])} disabled={loading}><Play size={16}/>{gmail.connected?"Testar envio real":"Conecte o Gmail para testar"}</button></div><div className="flow-visual"><FlowNode icon={<Webhook/>} label="Formulário" sub="Novo contato"/><FlowLine/><FlowNode icon={<Bot/>} label="IA classifica" sub="Intenção e prioridade" active/><FlowLine/><FlowNode icon={<Target/>} label="Histórico" sub="Execução registrada"/><FlowLine/><FlowNode icon={<Mail/>} label="Gmail" sub={gmail.connected?"Conta conectada":"Aguardando conexão"}/></div></section><div className="grid-two"><AutomationList automations={automations.slice(0,3)} onRun={openTest} onAll={()=>setTab("automations")}/><RunList runs={runs.slice(0,4)} onAll={()=>setTab("runs")}/></div></>}
        {tab==="automations"&&<div className="automation-grid">{automations.map(item=><article className="automation-card" key={item.id}><div className="card-top"><span className="automation-icon"><Zap size={20}/></span><span className={`state ${item.status}`}>{statusLabel[item.status]}</span></div><h3>{item.name}</h3><p>{item.description}</p><div className="mini-flow"><span>{item.triggerType}</span><ChevronRight size={14}/><span>{item.actionType}</span></div><div className="card-stats"><span><strong>{item.runs}</strong> execuções reais</span><span><strong>{item.successRate}%</strong> sucesso</span></div><button className="outline" onClick={()=>openTest(item)}><Play size={15}/>Testar fluxo</button></article>)}</div>}
        {tab==="runs"&&<section className="panel full"><div className="panel-head"><div><h2>Execuções recentes</h2><p>Somente os fluxos executados neste navegador</p></div><button className="icon-button" onClick={()=>void loadData()}><RefreshCw size={17}/></button></div><RunTable runs={runs}/></section>}
      </div>
    </section>
    {dialog&&<div className="modal-backdrop" onMouseDown={()=>setDialog(false)}><div className="modal" onMouseDown={event=>event.stopPropagation()}><button className="modal-close" onClick={()=>setDialog(false)}><X size={18}/></button><span className="modal-icon"><Zap/></span><h2>Criar nova automação</h2><p>Configure um fluxo inteligente em poucos passos.</p><form onSubmit={createAutomation}><label>Nome da automação<input value={form.name} onChange={event=>setForm({...form,name:event.target.value})} placeholder="Ex.: Qualificar leads do site" required/></label><label>Descrição<textarea value={form.description} onChange={event=>setForm({...form,description:event.target.value})} placeholder="O que este fluxo resolve?"/></label><div className="form-row"><label>Gatilho<select value={form.triggerType} onChange={event=>setForm({...form,triggerType:event.target.value})}><option>Novo formulário</option><option>Novo webhook</option><option>Agendamento</option><option>Lead qualificado</option></select></label><label>Ação final<select value={form.actionType} onChange={event=>setForm({...form,actionType:event.target.value})}><option>IA + CRM</option><option>IA + E-mail</option><option>Criar tarefa</option><option>CRM + E-mail</option></select></label></div><button className="primary submit" disabled={loading}>{loading?"Salvando…":"Criar automação"}<ArrowRight size={17}/></button></form></div></div>}
    {testAutomation&&<div className="modal-backdrop" onMouseDown={()=>setTestAutomation(null)}><div className="modal" onMouseDown={event=>event.stopPropagation()}><button className="modal-close" onClick={()=>setTestAutomation(null)}><X size={18}/></button><span className="modal-icon"><Mail/></span><h2>Testar automação real</h2><p>A mensagem será enviada por <strong>{gmail.email}</strong>, a conta autorizada pelo Google.</p><form onSubmit={runFlow}><label>Nome do contato<input value={lead.contactName} onChange={event=>setLead({...lead,contactName:event.target.value})} placeholder="Nome do destinatário" required maxLength={100}/></label><label>E-mail destinatário<input type="email" value={lead.contactEmail} onChange={event=>setLead({...lead,contactEmail:event.target.value})} placeholder="destinatario@exemplo.com" required/></label><label>Mensagem para classificar<textarea value={lead.message} onChange={event=>setLead({...lead,message:event.target.value})} required maxLength={3000}/></label><small>O BrunaFlow usa sua autorização apenas para consultar métricas da caixa e enviar este teste. Cada destinatário pode receber um teste a cada 10 minutos.</small><button className="primary submit" disabled={loading}>{loading?"Executando…":"Classificar e enviar"}<ArrowRight size={17}/></button></form></div></div>}
    {about&&<div className="modal-backdrop" onMouseDown={()=>setAbout(false)}><div className="modal about" onMouseDown={event=>event.stopPropagation()}><button className="modal-close" onClick={()=>setAbout(false)}><X size={18}/></button><span className="eyebrow">SOBRE O PROJETO</span><h2>Como o BrunaFlow AI funciona</h2><p>Cada visitante conecta a própria conta Gmail por autorização OAuth. Senhas nunca passam pelo BrunaFlow.</p><div className="about-steps"><div><Mail/><span><b>1. Conecta</b><small>O Google autoriza métricas da caixa e envio na conta escolhida.</small></span></div><div><Webhook/><span><b>2. Recebe</b><small>Formulário ou webhook inicia o fluxo.</small></span></div><div><Bot/><span><b>3. Entende</b><small>A IA classifica intenção e prioridade.</small></span></div><div><Database/><span><b>4. Registra</b><small>O resultado real atualiza métricas e histórico.</small></span></div></div><div className="tech-note"><Cloud/><span><b>Arquitetura demonstrada</b><small>Next.js, TypeScript, Cloudflare Workers, D1, OAuth 2.0, Gmail API, webhooks e IA com fallback.</small></span></div></div></div>}
    {notice&&<div className="toast"><Check size={17}/>{notice}</div>}
  </main>
}

function GmailConnection({gmail,syncing,onSync,onDisconnect}:{gmail:GmailStatus;syncing:boolean;onSync:()=>void;onDisconnect:()=>void}){return <section className={`gmail-card ${gmail.connected?"connected":""}`}><span className="gmail-icon"><Mail/></span><div><span className="eyebrow">INTEGRAÇÃO DE E-MAIL</span><h2>{gmail.connected?gmail.email:"Conecte sua conta Gmail"}</h2><p>{gmail.connected?`Caixa sincronizada: ${gmail.inboxMessages||0} recebidas, ${gmail.unreadMessages||0} não lidas e ${gmail.sentMessages||0} enviadas.`:"Autorize o BrunaFlow a ler métricas e enviar mensagens pela sua conta. Sua senha não é compartilhada."}</p></div><div className="gmail-actions">{gmail.connected?<><button className="outline compact" onClick={onSync} disabled={syncing}><RefreshCw size={15}/>{syncing?"Sincronizando":"Sincronizar"}</button><button className="icon-button" onClick={onDisconnect} title="Desconectar Gmail"><LogOut size={16}/></button></>:<a className="primary" href="/api/integrations/gmail/start"><Mail size={16}/>Conectar Gmail</a>}</div></section>}
function Metric({icon,label,value,hint,tone}:{icon:React.ReactNode;label:string;value:string;hint:string;tone:string}){return <article className="metric"><span className={`metric-icon ${tone}`}>{icon}</span><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></article>}
function FlowNode({icon,label,sub,active}:{icon:React.ReactNode;label:string;sub:string;active?:boolean}){return <div className={`flow-node ${active?"active":""}`}><span>{icon}</span><b>{label}</b><small>{sub}</small></div>}
function FlowLine(){return <span className="flow-line"><i/></span>}
function AutomationList({automations,onRun,onAll}:{automations:Automation[];onRun:(automation:Automation)=>void;onAll:()=>void}){return <section className="panel"><div className="panel-head"><div><h2>Automações</h2><p>Contadores baseados em execuções reais</p></div><button className="text-link" onClick={onAll}>Ver todas <ArrowRight size={14}/></button></div><div className="list">{automations.map(item=><div className="automation-row" key={item.id}><span className="automation-icon"><Zap size={17}/></span><div><b>{item.name}</b><small>{item.runs} {item.runs===1?"execução registrada":"execuções registradas"}</small></div><span className={`state ${item.status}`}>{statusLabel[item.status]}</span><button className="icon-button" onClick={()=>onRun(item)} title="Executar"><Play size={15}/></button></div>)}</div></section>}
function RunList({runs,onAll}:{runs:Run[];onAll:()=>void}){return <section className="panel"><div className="panel-head"><div><h2>Atividade recente</h2><p>Últimas execuções reais</p></div><button className="text-link" onClick={onAll}>Ver histórico <ArrowRight size={14}/></button></div>{runs.length?<div className="list">{runs.map(run=><div className="run-row" key={run.id}><span className={`run-dot ${run.status}`}><Check size={13}/></span><div><b>{run.contactName}</b><small>{run.automationName}</small></div><div className="run-meta"><b>{run.classification}</b><small>{providerLabel(run.provider)} · {relativeTime(run.createdAt)}</small></div></div>)}</div>:<EmptyState/>}</section>}
function RunTable({runs}:{runs:Run[]}){if(!runs.length)return <EmptyState/>;return <div className="table-wrap"><table><thead><tr><th>Contato</th><th>Automação</th><th>Classificação</th><th>IA</th><th>Status</th><th>Duração</th><th></th></tr></thead><tbody>{runs.map(run=><tr key={run.id}><td><strong>{run.contactName}</strong><small>Prioridade {run.priority.toLowerCase()}</small></td><td>{run.automationName}</td><td><span className="tag">{run.classification}</span></td><td>{providerLabel(run.provider)}</td><td><span className={`state ${run.status}`}>{statusLabel[run.status]||run.status}</span></td><td>{(run.durationMs/1000).toFixed(1)}s</td><td title={run.emailDraft||"Sem rascunho"}><MoreHorizontal size={17}/></td></tr>)}</tbody></table></div>}
function EmptyState(){return <div className="empty-state"><Activity size={20}/><b>Nenhuma execução ainda</b><small>Conecte o Gmail e teste um fluxo para gerar dados reais.</small></div>}
function providerLabel(value:string){return value==="groq"?"Groq":value==="gemini"?"Gemini":"Demonstração"}
function relativeTime(value:string){const mins=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/60000));return mins<1?"agora":mins<60?`há ${mins} min`:`há ${Math.floor(mins/60)}h`}
