import { and, desc, eq, gte, sql } from "drizzle-orm";
import { getDb } from "../db";
import { automations, deliveryAttempts, executions, gmailConnections } from "../db/schema";
import { classifyLead } from "./lead-ai";
import { sendTestEmail } from "./gmail";
import { decryptToken } from "./google-oauth";

type Input={automationId?:number;automationName?:string;contactName:string;contactEmail:string;message:string;ipAddress?:string;ownerHash?:string};
export async function executeLeadWorkflow(input:Input){const db=getDb();const email=input.contactEmail.trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error("Informe um e-mail destinatário válido.");const emailHash=await hash(email);const ipHash=await hash(input.ipAddress||"unknown");const [recentEmail]=await db.select({count:sql<number>`count(*)`}).from(deliveryAttempts).where(and(eq(deliveryAttempts.emailHash,emailHash),gte(deliveryAttempts.createdAt,sql`datetime('now','-10 minutes')`)));if(Number(recentEmail?.count||0)>0)throw new Error("Este e-mail já recebeu um teste recentemente. Aguarde 10 minutos.");const [recentIp]=await db.select({count:sql<number>`count(*)`}).from(deliveryAttempts).where(and(eq(deliveryAttempts.ipHash,ipHash),gte(deliveryAttempts.createdAt,sql`datetime('now','-1 hour')`)));if(Number(recentIp?.count||0)>=5)throw new Error("Limite de testes atingido nesta conexão. Tente novamente mais tarde.");let automationId=Number(input.automationId||0);let automationName=String(input.automationName||"");if(!automationId){const [selected]=await db.select().from(automations).orderBy(desc(automations.id)).limit(1);if(!selected)throw new Error("Nenhuma automação disponível.");automationId=selected.id;automationName=selected.name}let identity:undefined|{refreshToken:string;email:string};if(input.ownerHash){const [connection]=await db.select().from(gmailConnections).where(eq(gmailConnections.sessionHash,input.ownerHash)).limit(1);if(!connection)throw new Error("Conecte seu Gmail antes de executar o fluxo.");identity={refreshToken:await decryptToken(connection.encryptedRefreshToken),email:connection.email}}const started=Date.now();const result=await classifyLead({name:input.contactName,message:input.message,automationName});const emailResult=await sendTestEmail(email,`BrunaFlow AI: ${result.classification}`,result.emailDraft||`Olá, ${input.contactName}! Obrigada pelo contato.`,identity);if(!emailResult.sent)throw new Error("Conecte um Gmail para enviar a mensagem.");const [run]=await db.insert(executions).values({ownerHash:input.ownerHash||"webhook",automationId,automationName,contactName:input.contactName.slice(0,100),classification:result.classification,priority:result.priority,status:"success",attempts:1,durationMs:Date.now()-started,timeSavedMinutes:10,provider:result.provider,emailDraft:result.emailDraft}).returning();if(emailResult.sent)await db.insert(deliveryAttempts).values({emailHash,ipHash});return{run,analysis:{summary:result.summary,model:result.model},email:emailResult}}
async function hash(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes)).map(byte=>byte.toString(16).padStart(2,"0")).join("")}
