import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const emailTemplates=sqliteTable("email_templates",{id:integer("id").primaryKey({autoIncrement:true}),ownerHash:text("owner_hash").notNull(),name:text("name").notNull(),subject:text("subject").notNull(),body:text("body").notNull(),aiGenerated:integer("ai_generated",{mode:"boolean"}).notNull().default(false),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`)},table=>({ownerIndex:index("email_templates_owner_idx").on(table.ownerHash)}));
export const automations=sqliteTable("automations",{id:integer("id").primaryKey({autoIncrement:true}),ownerHash:text("owner_hash").notNull().default("template"),name:text("name").notNull(),description:text("description").notNull().default(""),triggerType:text("trigger_type").notNull(),actionType:text("action_type").notNull(),templateId:integer("template_id").references(()=>emailTemplates.id,{onDelete:"set null"}),status:text("status").notNull().default("active"),runs:integer("runs").notNull().default(0),successRate:real("success_rate").notNull().default(100),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)},table=>({ownerIndex:index("automations_owner_idx").on(table.ownerHash)}));
export const executions=sqliteTable("executions",{id:integer("id").primaryKey({autoIncrement:true}),ownerHash:text("owner_hash").notNull().default("legacy"),automationId:integer("automation_id").notNull().references(()=>automations.id),automationName:text("automation_name").notNull(),contactName:text("contact_name").notNull(),classification:text("classification").notNull(),priority:text("priority").notNull(),status:text("status").notNull(),attempts:integer("attempts").notNull().default(1),durationMs:integer("duration_ms").notNull(),timeSavedMinutes:integer("time_saved_minutes").notNull().default(10),provider:text("provider").notNull().default("simulation"),emailDraft:text("email_draft").notNull().default(""),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)},table=>({ownerCreatedIndex:index("executions_owner_created_idx").on(table.ownerHash,table.createdAt)}));
export const deliveryAttempts=sqliteTable("delivery_attempts",{id:integer("id").primaryKey({autoIncrement:true}),emailHash:text("email_hash").notNull(),ipHash:text("ip_hash").notNull(),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)},table=>({emailCreatedIndex:index("delivery_attempts_email_created_idx").on(table.emailHash,table.createdAt),ipCreatedIndex:index("delivery_attempts_ip_created_idx").on(table.ipHash,table.createdAt)}));
export const gmailConnections=sqliteTable("gmail_connections",{id:integer("id").primaryKey({autoIncrement:true}),sessionHash:text("session_hash").notNull().unique(),email:text("email").notNull(),encryptedRefreshToken:text("encrypted_refresh_token").notNull(),scopes:text("scopes").notNull().default(""),connectedAt:text("connected_at").notNull().default(sql`CURRENT_TIMESTAMP`),lastSyncedAt:text("last_synced_at")});
export const webhookKeys=sqliteTable("webhook_keys",{id:integer("id").primaryKey({autoIncrement:true}),sessionHash:text("session_hash").notNull().unique(),keyHash:text("key_hash").notNull().unique(),keyPrefix:text("key_prefix").notNull(),active:integer("active",{mode:"boolean"}).notNull().default(true),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),lastUsedAt:text("last_used_at")});
export const sentEmails=sqliteTable("sent_emails",{id:integer("id").primaryKey({autoIncrement:true}),ownerHash:text("owner_hash").notNull(),executionId:integer("execution_id").references(()=>executions.id,{onDelete:"set null"}),automationId:integer("automation_id").references(()=>automations.id,{onDelete:"set null"}),templateId:integer("template_id").references(()=>emailTemplates.id,{onDelete:"set null"}),recipientEmail:text("recipient_email").notNull(),recipientName:text("recipient_name").notNull().default(""),subject:text("subject").notNull(),body:text("body").notNull(),status:text("status").notNull().default("sent"),senderEmail:text("sender_email").notNull().default(""),sentAt:text("sent_at").notNull().default(sql`CURRENT_TIMESTAMP`)},table=>({ownerSentIndex:index("sent_emails_owner_sent_idx").on(table.ownerHash,table.sentAt)}));
